"""add product category relation

Revision ID: 32afacfb9e08
Revises: 7ff31e7375a2
Create Date: 2019-10-20 08:07:39.710245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32afacfb9e08'
down_revision = '7ff31e7375a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    # ### end Alembic commands ###
